{{- $upstreamAgent := index .Values "upstream-spire-agent" }}
{{- $joinToken := $upstreamAgent.joinToken | default dict }}
{{- if $joinToken.enabled }}
{{- if $joinToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-upstream-join-token" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: default
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: agent-upstream
type: Opaque
stringData:
  token: {{ $joinToken.value | quote }}
{{- end }}
{{- end }}
