apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: slim-dev
  namespace: argocd
spec:
  description: AGNTCY SLIM Project - Dev
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/agntcy/slim-staging
  - ghcr.io
status: {}
