{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $i, $north := .Values.service.north }}
    - port: {{ $north.port }}
      targetPort: {{ $north.name | default (printf "north-%d" $i) }}
      protocol: TCP
      name: {{ $north.name | default (printf "north-%d" $i) }}
    {{- end }}
    {{- range $i, $south := .Values.service.south }}
    - port: {{ $south.port }}
      targetPort: {{ $south.name | default (printf "south-%d" $i) }}
      protocol: TCP
      name: {{ $south.name | default (printf "south-%d" $i) }}
    {{- end }}
  selector:
    {{- include "control-plane.selectorLabels" . | nindent 4 }}
