{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slim.fullname" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.slim.overrideConfig }}
    {{- tpl (toYaml .Values.slim.overrideConfig) . | nindent 4 }}
    {{- else }}
    {{- $config := fromYaml (tpl (toYaml .Values.slim.config) .) }}
    {{- $_ := set (index $config "services" "slim/0" "peers" "discovery") "port" (int (index .Values.slim.service.data 0).port) }}
    {{- toYaml $config | nindent 4 }}
    {{- end }}
