{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $isDaemonSet := eq .Values.slim.deploymentMode "DaemonSet" }}

apiVersion: apps/v1
kind: {{ .Values.slim.deploymentMode | default "Deployment" }}
metadata:
  name: {{ include "slim.fullname" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
spec:
  {{- if not $isDaemonSet }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.slim.replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slim.selectorLabels" . | nindent 6 }}
  {{- if $isDaemonSet }}
  updateStrategy:
    type: {{ .Values.slim.updateStrategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.slim.updateStrategy.type | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.slim.updateStrategy.rollingUpdate.maxUnavailable | default 1 }}
    {{- end }}
  {{- else }}
  strategy:
    type: {{ .Values.slim.updateStrategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.slim.updateStrategy.type | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.slim.updateStrategy.rollingUpdate.maxUnavailable | default 1 }}
      maxSurge: {{ .Values.slim.updateStrategy.rollingUpdate.maxSurge | default 1 }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "slim.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.slim.image.repository }}:{{ .Values.slim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slim.image.pullPolicy }}
          command:
            - "/slim"
          args:
            - "--config"
            - "/config.yaml"
          env:
            - name: SLIM_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.slim.extraEnv }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- range $i, $data := .Values.slim.service.data }}
            - name: {{ $data.name | default (printf "data-plane-%d" $i) }}
              containerPort: {{ $data.port }}
              protocol: TCP
            {{- end }}
            {{- range $i, $ctrl := .Values.slim.service.control }}
            - name: controller-{{ $i }}
              containerPort: {{ $ctrl.port }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.slim.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ (index .Values.slim.service.data 0).port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
{{- if eq .Values.spire.enabled true }}
            - name: spire-agent-socket
              mountPath: /tmp/spire-agent/public/
              readOnly: true
{{- end }}
{{- with .Values.slim.extraVolumeMounts }}
{{ toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "slim.fullname" . }}
        {{- with .Values.slim.extraVolumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
{{- if eq .Values.spire.enabled true }}
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory
{{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $isDaemonSet }}
      dnsPolicy: {{ .Values.slim.dnsPolicy | default "ClusterFirst" }}
      {{- end }}
